/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  verifier: string;
}
export type ExecuteMsg = {
  register_requirement: {
    requirements: RegisterRequirement;
  };
} | {
  give_me_some_drink: GiveMeSomeDrink;
} | {
  give_me_some_food: GiveMeSomeFood;
};
export type RegisterRequirement = {
  drink: {
    requirements: RouteVerificationRequirements;
  };
} | {
  food: {
    requirements: RouteVerificationRequirements;
  };
};
export type Binary = string;
export type TrustRegistry = "cheqd";
export interface RouteVerificationRequirements {
  issuer_source_or_data: IssuerSourceOrData[];
  presentation_required?: Binary | null;
}
export interface IssuerSourceOrData {
  data_or_location: Binary;
  source?: TrustRegistry | null;
}
export interface GiveMeSomeDrink {
  kind: string;
  proof: Binary;
}
export interface GiveMeSomeFood {
  kind: string;
  proof: Binary;
}
export type QueryMsg = "get_verifier_address";
export type String = string;