/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export type TrustRegistry = "cheqd";
export interface InstantiateMsg {
  init_registrations: InitRegistration[];
  max_presentation_len: number;
}
export interface InitRegistration {
  app_addr: string;
  app_admin: string;
  routes: RegisterRouteRequest[];
}
export interface RegisterRouteRequest {
  requirements: RouteVerificationRequirements;
  route_id: number;
}
export interface RouteVerificationRequirements {
  issuer_source_or_data: IssuerSourceOrData[];
  presentation_required?: Binary | null;
}
export interface IssuerSourceOrData {
  data_or_location: Binary;
  source?: TrustRegistry | null;
}
export type ExecuteMsg = {
  update_revocation_list: {
    app_addr: string;
    request: UpdateRevocationListRequest;
  };
} | {
  register: {
    app_addr: string;
    requests: RegisterRouteRequest[];
  };
} | {
  verify: {
    additional_requirements?: Binary | null;
    app_addr?: string | null;
    presentation: Binary;
    route_id: number;
  };
} | {
  update: {
    app_addr: string;
    route_criteria?: RouteVerificationRequirements | null;
    route_id: number;
  };
} | {
  deregister: {
    app_addr: string;
  };
};
export interface UpdateRevocationListRequest {
  revoke: number[];
  route_id: number;
  unrevoke: number[];
}
export type QueryMsg = {
  get_route_verification_key: {
    app_addr: string;
    route_id: number;
  };
} | {
  get_app_admin: {
    app_addr: string;
  };
} | {
  get_routes: {
    app_addr: string;
  };
} | {
  get_route_requirements: {
    app_addr: string;
    route_id: number;
  };
};
export type String = string;
export type NullableString = string | null;
export type ArrayOfUint64 = number[];