version: "3"

services:
  cheqd-node:
    image: ghcr.io/nymlab/cheqd-node:v2.0.1-arm64
    ports:
      - target: 26656
        published: 26656 # Tendermint peer-to-peer (P2P) port
      - target: 26657
        published: 26657 # Tendermint RPC port
    volumes:
      - ./scripts/:/tmp
    entrypoint: /tmp/cheqd-genesis.sh

  neutron-node:
    image: ghrc.io/nymlab/neutron-standalone:v3.0.5-arm64
    ports:
      - target: 1318
        published: 1317 # GRPC
      - target: 26656
        published: 25556 # Tendermint P2P port
      - target: 26657
        published: 25557 # Tendermint RPC port
    environment:
      - RUN_BACKGROUND=0
      - CHAINID=neutron-local-1

  relayer:
    image: ghcr.io/cosmos/relayer:v2.5.2
    depends_on:
      - cheqd-node
      - neutron-node
    volumes:
      - ./scripts/:/tmp
    entrypoint: /tmp/relayer-setup.sh # setup relayer and create client and connection
