/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _0 from "./SdjwtVerifier.types.js";
import * as _1 from "./RestaurantContract.types.js";
export namespace contracts {
  export const SdjwtVerifier = { ..._0 };
  export const RestaurantContract = { ..._1 };
}
