/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import type { ExecuteMsg, QueryMsg } from "../types/SdjwtVerifier.types";
import {
  Binary,
  TrustRegistry,
  InstantiateMsg,
  InitRegistration,
  InputRoutesRequirements,
  RouteVerificationRequirements,
  VerificationSource,
  AvidaVerifierTraitExecMsg,
  ExecMsg,
  AvidaVerifierTraitQueryMsg,
  QueryMsg1,
  NullableString,
  ArrayOfUint64,
} from "../types/SdjwtVerifier.types";
import type { CamelCasedProperties } from "type-fest";
export abstract class SdjwtVerifierExecuteMsgBuilder {
  static register = ({
    appAddr,
    routeCriteria,
  }: CamelCasedProperties<
    Extract<
      ExecuteMsg,
      {
        register: unknown;
      }
    >["register"]
  >): ExecuteMsg => {
    return {
      register: {
        app_addr: appAddr,
        route_criteria: routeCriteria,
      } as const,
    };
  };
  static verify = ({
    appAddr,
    presentation,
    routeId,
  }: CamelCasedProperties<
    Extract<
      ExecuteMsg,
      {
        verify: unknown;
      }
    >["verify"]
  >): ExecuteMsg => {
    return {
      verify: {
        app_addr: appAddr,
        presentation,
        route_id: routeId,
      } as const,
    };
  };
  static update = ({
    appAddr,
    routeCriteria,
    routeId,
  }: CamelCasedProperties<
    Extract<
      ExecuteMsg,
      {
        update: unknown;
      }
    >["update"]
  >): ExecuteMsg => {
    return {
      update: {
        app_addr: appAddr,
        route_criteria: routeCriteria,
        route_id: routeId,
      } as const,
    };
  };
  static deregister = ({
    appAddr,
  }: CamelCasedProperties<
    Extract<
      ExecuteMsg,
      {
        deregister: unknown;
      }
    >["deregister"]
  >): ExecuteMsg => {
    return {
      deregister: {
        app_addr: appAddr,
      } as const,
    };
  };
}
export abstract class SdjwtVerifierQueryMsgBuilder {
  static getRoutes = ({
    appAddr,
  }: CamelCasedProperties<
    Extract<
      QueryMsg,
      {
        get_routes: unknown;
      }
    >["get_routes"]
  >): QueryMsg => {
    return {
      get_routes: {
        app_addr: appAddr,
      } as const,
    };
  };
  static getRouteRequirements = ({
    appAddr,
    routeId,
  }: CamelCasedProperties<
    Extract<
      QueryMsg,
      {
        get_route_requirements: unknown;
      }
    >["get_route_requirements"]
  >): QueryMsg => {
    return {
      get_route_requirements: {
        app_addr: appAddr,
        route_id: routeId,
      } as const,
    };
  };
  static getRouteVerificationKey = ({
    appAddr,
    routeId,
  }: CamelCasedProperties<
    Extract<
      QueryMsg,
      {
        get_route_verification_key: unknown;
      }
    >["get_route_verification_key"]
  >): QueryMsg => {
    return {
      get_route_verification_key: {
        app_addr: appAddr,
        route_id: routeId,
      } as const,
    };
  };
}
